USE codeup_test_db;

INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES ('Elton John', 'Goodbye Yellow Brick Road', 1973, 8.5, 'rock, pop rock, glam rock'),
       ('Various artists', 'Grease: The Original Soundtrack from the Motion Picture', 1978, 14.4, 'Rock and roll'),
       ('The Beatles', 'Abbey Road', 1969, 14.4, 'Rock'),
       ('Nirvana', 'Nevermind', '1991', 16.7, 'Grunge, alternative rock'),
       ('Michael Jackson', 'Dangerous', 1991, 17.0, 'New jack swing, R&B, pop'),
       ('Dire Straits', 'Brothers in Arms', 1985, 17.7, 'Roots rock, blues rock, soft rock'),
       ('Various artists', 'Dirty Dancing', 1987, 17.9, 'Pop, rock, R&B'),
       ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 18.1, 'Film score'),
       ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 1967, 18.2, 'Rock'),
       ('Pink Floyd', 'The Wall', 1979, 18.7, 'Progressive rock'),
       ('Celine Dion', 'Let''s Talk About Love', 1997, 19.3, 'Pop, soft rock'),
       ('Madonna', 'The Immaculate Collection', 1990, 19.5, 'Pop, dance'),
       ('Bruce Springsteen', 'Born in the U.S.A.', 1984, 19.6, 'Heartland rock'),
       ('Santana', 'Supernatural', 1999, 20.5, 'Latin rock'),
       ('Celine Dion', 'Falling into You', 1996, 21.1, 'Pop, soft rock'),
       ('Michael Jackson', 'Bad', 1987, 21.1, 'Pop, rhythm and blues, funk and rock'),
       ('Guns N'' Roses', 'Appetite for Destruction', 1987, 21.9, 'Hard rock'),
       ('ABBA', 'Gold: Greatest Hits', 1992, 23.0, 'Pop, disco'),
       ('The Beatles', '1', 2000, 23.5, 'Rock'),
       ('Alanis Morissette', 'Jagged Little Pill', 1995, 24.3, 'Alternative rock'),
       ('Metallica', 'Metallica', 1991, 25.2, 'Heavy metal'),
       ('Adele', '21', 2011, 26.4, 'Pop, soul'),
       ('Led Zeppelin', 'Led Zeppelin IV', 1971, 29.0, 'Hard rock, heavy metal, folk rock'),
       ('Bee Gees', 'Saturday Night Fever', 1977, 21.6, 'Disco'),
       ('Meat Loaf', 'Bat Out of Hell', 1977, 21.7, 'Hard rock, glam rock, progressive rock'),
       ('Pink Floyd', 'The Dark Side of the Moon', 1973, 24.4, 'Progressive rock'),
       ('Fleetwood Mac', 'Rumours', 1977, 27.9, 'Soft rock'),
       ('AC/DC', 'Back in Black', 1980, 29.5, 'Hard rock'),
       ('Shania Twain', 'Come On Over', 1997, 29.6, 'Country, pop'),
       ('Eagles', 'Hotel California', 1976, 31.5, 'Soft rock'),
       ('Whitney Houston', 'The Bodyguard', 1992, 32.4, 'R&B, soul, pop, soundtrack'),
       ('Eagles', 'Their Greatest Hits (1971-1975)', 1976, 41.2, 'Country rock, soft rock, folk rock'),
       ('Michael Jackson', 'Thriller', 1982, 49.2, 'Pop, post-disco, funk, rock');